-- MySQL Script generated by MySQL Workbench
-- Tue Feb  5 18:50:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capasits
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capasits
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capasits` DEFAULT CHARACTER SET utf8 ;
USE `capasits` ;

-- -----------------------------------------------------
-- Table `capasits`.`Datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Datos` (
  `id_datos` INT NOT NULL,
  `ap_paterno` VARCHAR(30) NOT NULL,
  `ap_materno` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `nacionalidad` VARCHAR(60) NOT NULL,
  `edo_civil` VARCHAR(20) NOT NULL,
  `derecho` INT NOT NULL,
  `institucion` VARCHAR(99) NULL,
  `seg_popular` INT(10) NULL,
  `ocupacion` VARCHAR(60) NOT NULL,
  `origen` VARCHAR(60) NOT NULL,
  `calle` VARCHAR(99) NOT NULL,
  `numero` INT(5) NULL,
  `colonia` VARCHAR(99) NOT NULL,
  `codigo` INT(5) NOT NULL,
  `localidad` VARCHAR(99) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `telefono` INT(10) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_datos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Antecedentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Antecedentes` (
  `id_antecedentes` INT NOT NULL,
  `factor` VARCHAR(99) NOT NULL,
  `inicio_sex` DATETIME NOT NULL,
  `num_parejas` INT NOT NULL,
  `antico` INT NOT NULL,
  `metodo_antico` VARCHAR(99) NOT NULL,
  `fecha_diagnostico` DATETIME NOT NULL,
  `metodo_diagnostico` VARCHAR(60) NOT NULL,
  `fecha_pro_inf` DATETIME NOT NULL,
  `fecha_ini_man` DATETIME NOT NULL,
  PRIMARY KEY (`id_antecedentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Antecedentes_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Antecedentes_2` (
  `id_antecedentes_2` INT NOT NULL,
  `ant_heredofamiliares` VARCHAR(999) NOT NULL,
  `escolaridad` VARCHAR(45) NOT NULL,
  `vivienda` VARCHAR(30) NOT NULL,
  `viajes_rec` VARCHAR(99) NOT NULL,
  `conv_animales` INT NOT NULL,
  `animales` VARCHAR(99) NULL,
  `tabaquismo` INT NOT NULL,
  `tab_cantidad` INT NULL,
  `tab_frecuencia` VARCHAR(20) NULL,
  `tab_años` INT NULL,
  `alcoholismo` INT NOT NULL,
  `alc_cantidad` INT NULL,
  `alc_frecuencia` VARCHAR(20) NULL,
  `alc_anios` INT NULL,
  `inmunizacion` INT NOT NULL,
  `inm_cuales` VARCHAR(333) NULL,
  `cirugias` INT NOT NULL,
  `cirugias_cuales` VARCHAR(299) NULL,
  `fracturas` INT NOT NULL,
  `fracturas_cuales` VARCHAR(299) NULL,
  `alergias` INT NOT NULL,
  `alergias_cuales` VARCHAR(299) NULL,
  `otros_medicamentos` INT NOT NULL,
  `otros_med_cuales` VARCHAR(299) NULL,
  PRIMARY KEY (`id_antecedentes_2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Paciente` (
  `ID_paciente` INT NOT NULL,
  `Antecedentes_id_antecedentes` INT NOT NULL,
  `Datos_id_datos` INT NOT NULL,
  `Antecedentes_2_id_antecedentes_2` INT NOT NULL,
  PRIMARY KEY (`ID_paciente`),
  INDEX `fk_Paciente_Antecedentes_idx` (`Antecedentes_id_antecedentes` ASC) VISIBLE,
  INDEX `fk_Paciente_Datos1_idx` (`Datos_id_datos` ASC) VISIBLE,
  INDEX `fk_Paciente_Antecedentes_21_idx` (`Antecedentes_2_id_antecedentes_2` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Antecedentes`
    FOREIGN KEY (`Antecedentes_id_antecedentes`)
    REFERENCES `capasits`.`Antecedentes` (`id_antecedentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Datos1`
    FOREIGN KEY (`Datos_id_datos`)
    REFERENCES `capasits`.`Datos` (`id_datos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Antecedentes_21`
    FOREIGN KEY (`Antecedentes_2_id_antecedentes_2`)
    REFERENCES `capasits`.`Antecedentes_2` (`id_antecedentes_2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Embarazo_ant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Embarazo_ant` (
  `id_embarazao_ant` INT NOT NULL,
  `embarazo_ant` INT NOT NULL,
  `perdida_pro` INT NOT NULL,
  `fecha_nac_pro` DATETIME NULL,
  `profilaxis_intra` INT NOT NULL,
  `profilaxis_intra_tipo` VARCHAR(50) NULL,
  `profilaxis_intra_tiempo` INT NULL,
  `profilaxis_pos` INT NULL,
  `profilaxis_pos_tipo` VARCHAR(40) NULL,
  `profilaxis_pos_tiempo` INT NULL,
  `metodo_res_emb` INT NULL,
  `lactancia` INT NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  PRIMARY KEY (`id_embarazao_ant`),
  INDEX `fk_Embarazo_ant_Paciente1_idx` (`Paciente_ID_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Embarazo_ant_Paciente1`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `capasits`.`Paciente` (`ID_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Hospitalizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Hospitalizacion` (
  `id_hospitalizacion` INT NOT NULL,
  `fecha_hos` DATETIME NOT NULL,
  `diagnostico_hos` VARCHAR(99) NOT NULL,
  `tratamiento_hos` VARCHAR(99) NOT NULL,
  `duracion_hos` INT NOT NULL,
  `hospital` VARCHAR(99) NOT NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  PRIMARY KEY (`id_hospitalizacion`),
  INDEX `fk_Hospitalizacion_Paciente1_idx` (`Paciente_ID_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitalizacion_Paciente1`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `capasits`.`Paciente` (`ID_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Cita` (
  `id_cita` INT NOT NULL,
  `peso` DECIMAL(3) NULL,
  `talla` DECIMAL(3) NULL,
  `presion_art` INT NULL,
  `frecuencia_car` INT NULL,
  `frecuencia_res` INT NULL,
  `temperatura` DECIMAL(2) NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_Cita_Paciente1_idx` (`Paciente_ID_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Cita_Paciente1`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `capasits`.`Paciente` (`ID_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Embarazo_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Embarazo_act` (
  `id_embarazo_act` INT NOT NULL,
  `embarazo_act` INT NOT NULL,
  `semana_ges` INT NOT NULL,
  `trata_antire_opc` INT NOT NULL,
  `semana_ini_trata_antire` INT NULL,
  `esquemas_ant` INT NOT NULL,
  `esquemas_ant_cuales` VARCHAR(99) NULL,
  `profilaxis_intra` INT NOT NULL,
  `profilaxis_intra_tipo` VARCHAR(99) NULL,
  `profilaxis_intra_tiempo` INT NULL,
  `Cita_id_cita` INT NOT NULL,
  PRIMARY KEY (`id_embarazo_act`),
  INDEX `fk_Embarazo_act_Cita1_idx` (`Cita_id_cita` ASC) VISIBLE,
  CONSTRAINT `fk_Embarazo_act_Cita1`
    FOREIGN KEY (`Cita_id_cita`)
    REFERENCES `capasits`.`Cita` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Estadificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Estadificacion` (
  `id_estadificacion` INT NOT NULL,
  `estadio` VARCHAR(1) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `tratamiento` VARCHAR(99) NOT NULL,
  `suspension` INT NOT NULL,
  `motivo` VARCHAR(299) NOT NULL,
  `terminacion` DATETIME NOT NULL,
  `Cita_id_cita` INT NOT NULL,
  PRIMARY KEY (`id_estadificacion`),
  INDEX `fk_Estadificacion_Cita1_idx` (`Cita_id_cita` ASC) VISIBLE,
  CONSTRAINT `fk_Estadificacion_Cita1`
    FOREIGN KEY (`Cita_id_cita`)
    REFERENCES `capasits`.`Cita` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Tratamiento_antiretroviral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Tratamiento_antiretroviral` (
  `id_antiretroviral` INT NOT NULL,
  `tratamiento_antiretroviral` VARCHAR(30) NOT NULL,
  `fecha_ini_trata` DATETIME NOT NULL,
  `suspension_trata_anti` INT NOT NULL,
  `fecha_suspension` DATETIME NOT NULL,
  `motivo_suspension` VARCHAR(199) NOT NULL,
  `carga_viral` INT NOT NULL,
  `logaritmo` INT NOT NULL,
  `cd4_por` DECIMAL(2) NOT NULL,
  `cd4_num` INT NOT NULL,
  `cd8_num` INT NOT NULL,
  `cd8_por` DECIMAL(2) NOT NULL,
  `efectos_adversos` INT NOT NULL,
  `efectos_adversos_cuales` VARCHAR(299) NULL,
  `fecha_efecto` DATETIME NULL,
  `medicamento_efecto_causa` VARCHAR(99) NULL,
  `tratamiento_correctivo` VARCHAR(299) NULL,
  `esquemas_ant` INT NOT NULL,
  `esquemas_ant_cuales` VARCHAR(299) NULL,
  `adherencia` INT NOT NULL,
  `Cita_id_cita` INT NOT NULL,
  PRIMARY KEY (`id_antiretroviral`),
  INDEX `fk_Tratamiento_antiretroviral_Cita1_idx` (`Cita_id_cita` ASC) VISIBLE,
  CONSTRAINT `fk_Tratamiento_antiretroviral_Cita1`
    FOREIGN KEY (`Cita_id_cita`)
    REFERENCES `capasits`.`Cita` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Adherencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Adherencia` (
  `id_adherencia` INT NOT NULL,
  `adherencia_por` DECIMAL(2) NOT NULL,
  `esquema` VARCHAR(10) NOT NULL,
  `modificacion_esquema` INT NOT NULL,
  `adh_anterior` VARCHAR(45) NOT NULL,
  `Tratamiento_antiretroviral_id_antiretroviral` INT NOT NULL,
  PRIMARY KEY (`id_adherencia`),
  INDEX `fk_Adherencia_Tratamiento_antiretroviral1_idx` (`Tratamiento_antiretroviral_id_antiretroviral` ASC) VISIBLE,
  CONSTRAINT `fk_Adherencia_Tratamiento_antiretroviral1`
    FOREIGN KEY (`Tratamiento_antiretroviral_id_antiretroviral`)
    REFERENCES `capasits`.`Tratamiento_antiretroviral` (`id_antiretroviral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Tratamiendo_profilaxis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Tratamiendo_profilaxis` (
  `id_trata_profilaxis` INT NOT NULL,
  `fecha_ini` DATETIME NOT NULL,
  `farmaco` VARCHAR(199) NOT NULL,
  `indicacion` VARCHAR(299) NOT NULL,
  `suspension` INT NOT NULL,
  `fecha_susp` DATETIME NULL,
  `motivos_susp` VARCHAR(299) NULL,
  `profilaxis_farmaco` VARCHAR(99) NOT NULL,
  `Embarazo_act_id_embarazo_act` INT NOT NULL,
  PRIMARY KEY (`id_trata_profilaxis`),
  INDEX `fk_Tratamiendo_profilaxis_Embarazo_act1_idx` (`Embarazo_act_id_embarazo_act` ASC) VISIBLE,
  CONSTRAINT `fk_Tratamiendo_profilaxis_Embarazo_act1`
    FOREIGN KEY (`Embarazo_act_id_embarazo_act`)
    REFERENCES `capasits`.`Embarazo_act` (`id_embarazo_act`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Tratamiendo_etapas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Tratamiendo_etapas` (
  `id_tratamiendo_etapas` INT NOT NULL,
  `etapa` INT NOT NULL,
  `farmaco` VARCHAR(45) NOT NULL,
  `fecha_ini` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `Cita_id_cita` INT NOT NULL,
  PRIMARY KEY (`id_tratamiendo_etapas`),
  INDEX `fk_Tratamiendo_etapas_Cita1_idx` (`Cita_id_cita` ASC) VISIBLE,
  CONSTRAINT `fk_Tratamiendo_etapas_Cita1`
    FOREIGN KEY (`Cita_id_cita`)
    REFERENCES `capasits`.`Cita` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Tratamiento_antifimico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Tratamiento_antifimico` (
  `id_tratamiento_antifimico` INT NOT NULL,
  `fecha_diagnostico` DATETIME NOT NULL,
  `localizacion` VARCHAR(199) NOT NULL,
  `metodo_diagnostico` VARCHAR(199) NOT NULL,
  `tb` INT NOT NULL,
  `curado` VARCHAR(30) NOT NULL,
  `trata_virgen` VARCHAR(199) NOT NULL,
  `recaida` INT NOT NULL,
  `fecha_recaida` DATETIME NULL,
  `trata_recaida` VARCHAR(199) NULL,
  `trata_tb_multi` INT NOT NULL,
  `Cita_id_cita` INT NOT NULL,
  PRIMARY KEY (`id_tratamiento_antifimico`),
  INDEX `fk_Tratamiento_antifimico_Cita1_idx` (`Cita_id_cita` ASC) VISIBLE,
  CONSTRAINT `fk_Tratamiento_antifimico_Cita1`
    FOREIGN KEY (`Cita_id_cita`)
    REFERENCES `capasits`.`Cita` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Usuario` (
  `idAdmin` INT NOT NULL,
  `User` VARCHAR(45) NULL,
  `Pass` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`TipoU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`TipoU` (
  `idTipoU` INT NOT NULL,
  `TipoNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capasits`.`Usuario_Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capasits`.`Usuario_Tipo` (
  `Usuario_idAdmin` INT NOT NULL,
  `TipoU_idTipoU` INT NOT NULL,
  INDEX `fk_Usuario_Tipo_Usuario1_idx` (`Usuario_idAdmin` ASC) VISIBLE,
  INDEX `fk_Usuario_Tipo_TipoU1_idx` (`TipoU_idTipoU` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Tipo_Usuario1`
    FOREIGN KEY (`Usuario_idAdmin`)
    REFERENCES `capasits`.`Usuario` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Tipo_TipoU1`
    FOREIGN KEY (`TipoU_idTipoU`)
    REFERENCES `capasits`.`TipoU` (`idTipoU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
